swagger: "2.0"
info:
  title: Car Rental API
  version: 1.0.0
  description: A simple API for managing car rentals.
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /cars:
    get:
      summary: Get a list of cars
      responses:
        '200':
          description: A list of cars
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: The unique identifier for the car
                brand:
                  type: string
                  description: The brand of the car
                year:
                  type: integer
                  description: The manufacturing year of the car
                transmission:
                  type: string
                  description: The type of transmission (e.g., automatic, manual)
                doors:
                  type: integer
                  description: The number of doors on the car
                renter_dob:
                  type: string
                  format: date-time
                  description: The date of birth of the renter (minimum age requirement)
                horsepower:
                  type: integer
                  description: The horsepower of the car
                price:
                  type: number
                  format: float
                  description: The rental price of the car
                status:
                  type: string
                  description: The availability status of the car (e.g., available, rented)
                variety:
                  type: string
                  description: The variety or type of the car (e.g., SUV, sedan)
  /cars/{id}:
    get:
      summary: Get a single car by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the car to retrieve
      responses:
        '200':
          description: Details of a single car
          schema:
            type: object
            properties:
              id:
                type: integer
                description: The unique identifier for the car
              brand:
                type: string
                description: The brand of the car
              year:
                type: integer
                description: The manufacturing year of the car
              transmission:
                type: string
                description: The type of transmission (e.g., automatic, manual)
              doors:
                type: integer
                description: The number of doors on the car
              renter_dob:
                type: string
                format: date-time
                description: The date of birth of the renter (minimum age requirement)
              horsepower:
                type: integer
                description: The horsepower of the car
              price:
                type: number
                format: float
                description: The rental price of the car
              status:
                type: string
                description: The availability status of the car (e.g., available, rented)
              variety:
                type: string
                description: The variety or type of the car (e.g., SUV, sedan)
        '404':
          description: Car not found
